name: Semgrep

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - '**' # run for all branches
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
      - '**/*.py' # run for change the python folder
  schedule:
    - cron: '40 2 * * *'

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep
        run: semgrep ci --config p/security-audit --config .github/workflows/custom-rules.yml

